**22/12/2025**

## FEATURE ENGINEERING ##

- It is the process of transforming raw data into features that make machine learning algorithms work better.
    - to improve performance of ML models
    - it can improve quality and relevance of features

**Categorical Features**
- Groups of data
    - will include Binary Features (0 and 1)
    - sex - M F
    - Survived - Yes No
    - Bool data type
    - Category data type - 
    - Ordinal data type - you can set up a scale in the cateogry - eg. small medium large, cold warm hot

**Numerical Features**
- where there are numbers
- will include 'float' and 'integers' both
- continous values
- grouping up will not make much sense (unless doing clustering)

In [4]:
import pandas as pd
import seaborn as sns
import numpy as np

In [5]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
iris.info()

#SNAS: if the Dtype is object,bool,category it is categorical features
#SNAS: if the Dtype is float,int it is numerical features

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Can you check for Titanic dataset?
- how many categorical features?
- how many numerical features?

In [7]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
titanic.info()

#SNAS: Titanic categorical features: 9, numerical: 6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [9]:
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [10]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

**Encoding**

In [11]:
# label encoding
# column that you can encode

penguins['species'].unique()

# {  }

species_codes = {
    'Adelie'    :   0,
    'Chinstrap' :   1,
    'Gentoo'    :   2
}

penguins['species_encoded'] = penguins['species'].map(species_codes)    #SNAS: passing a dictionary

penguins['species']

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

In [12]:
# pandas map

s = pd.Series(['cat', 'cow', 'dog'])
print(s)

s2 = s.map({'cat' : 'kitten', 'cow' : 'calf', 'dog' : 'puppy'})
print(s2)

0    cat
1    cow
2    dog
dtype: object
0    kitten
1      calf
2     puppy
dtype: object

**copy and view**

In [ ]:
# inbuilt map function in Python

words = ['apple','banana','cherry']
lengths = map(len, words)
list(lengths)

[5, 6, 6]

In [14]:
#SNAS: map in pandas dataframe

In [15]:
# factorize
# species still contains the species names

# factorize will take the column and assigns numbers to the new groups
pd.factorize(penguins['species'])

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 Index(['Adelie', 'Chinstrap', 'Gentoo'], dtype='object'))

In [16]:
#SNAS: one of the student's answer below

penguins['species_factorize'],unique_penguins = pd.factorize(penguins['species'])
#penguins.sample(10)

In [17]:
#SNAS: sir answer as below

x, y = pd.factorize(penguins['species'])

penguins['species_factorize'] = x
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,species_factorize
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0
...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2

In [24]:
df = penguins.copy()

df['species'] = df['species'].astype('category')    #SNAS: to change datatype in pandas
#SNAS in above example, the species datatype will be category datatype

df['species_cat_encoded'] = df['species'].cat.codes #SNAS: species_cat_encoded is a new column
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,species_factorize,island_encoded,island_factorized,species_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,2,0,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,2,0,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,2,0,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,2,0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,0,1,2
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,0,1,2
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,0,1,2
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,0,1,2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,0,1,2

**Exercise**

- apply the three methods to island column
- manually applying the label codes
- using the factorize method
- using the category

In [19]:
# Exercise: to do for island instead. my answer as below. I think not correct

penguins['island'].unique()

island_codes = {
    'Biscoe'    :   0,
    'Dream'     :   1,
    'Torgersen' :   2
}

penguins['island_encoded'] = penguins['island'].map(island_codes)    #SNAS: passing a dictionary

penguins['island_encoded']

0      2
1      2
2      2
3      2
4      2
      ..
339    0
340    0
341    0
342    0
343    0
Name: island_encoded, Length: 344, dtype: int64

In [20]:
#SNAS: my answer as below

x, y = pd.factorize(penguins['island'])

penguins['island_factorized'] = x
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,species_factorize,island_encoded,island_factorized
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,2,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,2,0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,2,0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,2,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,0,1
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,0,1
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,0,1
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,0,1
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,0,1

In [25]:
#SNAS: my answer as below

df = penguins.copy()

df['island'] = df['island'].astype('category')    #SNAS: to change datatype in pandas
#SNAS in above example, the species datatype will be category datatype

df['island_cat_encoded'] = df['island'].cat.codes #SNAS: species_cat_encoded is a new column
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,species_factorize,island_encoded,island_factorized,island_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,2,0,2
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,2,0,2
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,2,0,2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,2,0,2
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,0,1,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,0,1,0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,0,1,0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,0,1,0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,0,1,0

In [22]:
df = df.drop(columns=['species_factorize'])
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,island_encoded,island_factorized,island_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,2,0,2
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,2,0,2
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,2,0,2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,2,0,2
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,0,1,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,0,1,0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,0,1,0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,0,1,0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,0,1,0

**Label Encoding using sklearn**

In [26]:
from sklearn.preprocessing import LabelEncoder

#create LabelEncoder instance
encoder = LabelEncoder()

df['species_sklearn_le'] = encoder.fit_transform(df['species'])

df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,species_factorize,island_encoded,island_factorized,island_cat_encoded
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,0,0,2,0,2
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,0,0,2,0,2
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,0,0,2,0,2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,0,0,2,0,2
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,0,0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2,2,0,1,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,2,2,0,1,0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,2,2,0,1,0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,2,2,0,1,0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,2,2,0,1,0

Multiple methods:

- manual - .map() - can be used on ordinal data (bool, )