**22/12/2025**

In [9]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
iris.sample(10)

     sepal_length  sepal_width  petal_length  petal_width     species
63            6.1          2.9           4.7          1.4  versicolor
149           5.9          3.0           5.1          1.8   virginica
23            5.1          3.3           1.7          0.5      setosa
119           6.0          2.2           5.0          1.5   virginica
19            5.1          3.8           1.5          0.3      setosa
130           7.4          2.8           6.1          1.9   virginica
30            4.8          3.1           1.6          0.2      setosa
147           6.5          3.0           5.2          2.0   virginica
50            7.0          3.2           4.7          1.4  versicolor
71            6.1          2.8           4.0          1.3  versicolor

In [20]:
# get dummies method changing categories into columns
# get dummies method - categories --> Columns
# automatically detects the catagorical columns as well 

df_onehot = pd.get_dummies(iris, columns=['species'])
df_onehot['species_setosa'].dtype

dtype('bool')

In [21]:
df_onehot.sample(10)

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
7,5.0,3.4,1.5,0.2,True,False,False
40,5.0,3.5,1.3,0.3,True,False,False
87,6.3,2.3,4.4,1.3,False,True,False
6,4.6,3.4,1.4,0.3,True,False,False
46,5.1,3.8,1.6,0.2,True,False,False
143,6.8,3.2,5.9,2.3,False,False,True
95,5.7,3.0,4.2,1.2,False,True,False
103,6.3,2.9,5.6,1.8,False,False,True
29,4.7,3.2,1.6,0.2,True,False,False
110,6.5,3.2,5.1,2.0,False,False,True

**Exercise**

Apply one hot encoding to penguins dataset for species and island.

In [5]:
#SNAS: my answer as below

penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [6]:
df_onehot2 = pd.get_dummies(penguins, columns=['species'])
df_onehot2
#df_onehot2['species_Adelie'].dtype

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_Adelie,species_Chinstrap,species_Gentoo
0,Torgersen,39.1,18.7,181.0,3750.0,Male,True,False,False
1,Torgersen,39.5,17.4,186.0,3800.0,Female,True,False,False
2,Torgersen,40.3,18.0,195.0,3250.0,Female,True,False,False
3,Torgersen,NaN,NaN,NaN,NaN,NaN,True,False,False
4,Torgersen,36.7,19.3,193.0,3450.0,Female,True,False,False
...,...,...,...,...,...,...,...,...,...
339,Biscoe,NaN,NaN,NaN,NaN,NaN,False,False,True
340,Biscoe,46.8,14.3,215.0,4850.0,Female,False,False,True
341,Biscoe,50.4,15.7,222.0,5750.0,Male,False,False,True
342,Biscoe,45.2,14.8,212.0,5200.0,Female,False,False,True
343,Biscoe,49.9,16.1,213.0,5400.0,Male,False,False,True

In [7]:
df_onehot3 = pd.get_dummies(penguins, columns=['island'])
df_onehot3

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,island_Biscoe,island_Dream,island_Torgersen
0,Adelie,39.1,18.7,181.0,3750.0,Male,False,False,True
1,Adelie,39.5,17.4,186.0,3800.0,Female,False,False,True
2,Adelie,40.3,18.0,195.0,3250.0,Female,False,False,True
3,Adelie,NaN,NaN,NaN,NaN,NaN,False,False,True
4,Adelie,36.7,19.3,193.0,3450.0,Female,False,False,True
...,...,...,...,...,...,...,...,...,...
339,Gentoo,NaN,NaN,NaN,NaN,NaN,True,False,False
340,Gentoo,46.8,14.3,215.0,4850.0,Female,True,False,False
341,Gentoo,50.4,15.7,222.0,5750.0,Male,True,False,False
342,Gentoo,45.2,14.8,212.0,5200.0,Female,True,False,False
343,Gentoo,49.9,16.1,213.0,5400.0,Male,True,False,False

Get Dummies, it automatically ignores any missing values

In [22]:
df = pd.DataFrame([ 1,2,np.nan,1,1,1,3,3,3,2,2,2,3,3,3,1,1,1,1], columns= ["first"])
df.head()

df['first'].dtype

df['first'] = df['first'].astype('category')
df['first'].dtype

df_encoded = pd.get_dummies(df, columns=['first'], dummy_na=True)   #SNAS: dummy_na will show if there is a NaN value to be put into a category as well
df_encoded.head()
# df_encoded.info()

   first_1.0  first_2.0  first_3.0  first_nan
0       True      False      False      False
1      False       True      False      False
2      False      False      False       True
3       True      False      False      False
4       True      False      False      False

#### can also use sklearn.preprocessing method

- `OneHotEncoder`
- the other method to to label encoding?????? --> `LabelEncoder`

In [ ]:
# another methods for OneHotEncoding is from sklearn

from sklearn.preprocessing import OneHotEncoder

In [ ]:
# Creating the encoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Ignore the missing values if handle_unknown = 'ignore'"in class label encoding .ipynb"

In [15]:
encoder.fit_transform(iris)

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(150, 126))

In [23]:
iris_onehot = iris.copy()

encoder = OneHotEncoder( sparse_output = False, handle_unknown='ignore')

catagorical_cols = ['species']

ecoded_values = encoder.fit_transform(iris_onehot[catagorical_cols]) # species

# names of new columns, that don't exist yet
new_columns = encoder.get_feature_names_out(catagorical_cols)
new_columns
# ['species_setosa', 'species_versicolor', 'species_virginica']

# iris_onehot

# adding the columns to the dataframe

iris_onehot[new_columns] = ecoded_values

iris_onehot.drop(columns=['species'], inplace = True)
iris_onehot

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,0.0,0.0,1.0

pl , pw, sl, sw, species, setosa, virginica, versicolor

Species --> object

drop this column, before fitting into the model.
#SNAS: Because ML algorithm only accepts numerical value not string, so anything with text need to be converted to numerical values.

**Exercise**

Try to do both.
Label encoding and One Hot Encoding on
 
titanic dataset

In [24]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
titanic.info()  #SNAS: to know how many categorical dataset that need to be converted. Titanic categorical features: 9, numerical: 6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [26]:
titanic.sample(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
125,1,3,male,12.0,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
845,0,3,male,42.0,0,0,7.5500,S,Third,man,True,NaN,Southampton,no,True
67,0,3,male,19.0,0,0,8.1583,S,Third,man,True,NaN,Southampton,no,True
368,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,yes,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
419,0,3,female,10.0,0,2,24.1500,S,Third,child,False,NaN,Southampton,no,False
529,0,2,male,23.0,2,1,11.5000,S,Second,man,True,NaN,Southampton,no,False
373,0,1,male,22.0,0,0,135.6333,C,First,man,True,NaN,Cherbourg,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
424,0,3,male,18.0,1,1,20.2125,S,Third,man,True,NaN,Southampton,no,False
393,1,1,female,23.0,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
568,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
433,0,3,male,17.0,0,0,7.1250,S,Third,man,True,NaN,Southampton,no,True
260,0,3,male,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
398,0,2,male,23.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
251,0,3,female,29.0,1,1,10.4625,S,Third,woman,False,G,Southampton,no,False
83,0,1,male,28.0,0,0,47.1000,S,First,man,True,NaN,Southampton,no,True
661,0,3,male,40.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
57,0,3,male,28.5,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
384,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True

In [27]:
# SNAS: 1. label encoding

from sklearn.preprocessing import LabelEncoder

df = titanic.copy()

df['sex'] = df['sex'].astype('category')    #SNAS: to change datatype in pandas
#SNAS in above example, the species datatype will be category datatype

df['sex_cat_encoded'] = df['sex'].cat.codes #SNAS: species_cat_encoded is a new column
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_cat_encoded
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1

In [28]:
#create LabelEncoder instance
encoder = LabelEncoder()

df['sex_sklearn_le'] = encoder.fit_transform(df['sex'])
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_cat_encoded,sex_sklearn_le
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0,0
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,0,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,1,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,1,1

In [29]:
# SNAS: 2. one hot encoding

sex_onehot = titanic.copy()

encoder = OneHotEncoder(sparse_output = False, handle_unknown='ignore')

categorical_cols = ['sex']

ecoded_values = encoder.fit_transform(sex_onehot[categorical_cols]) # sex

# names of new columns, that don't exist yet
new_columns = encoder.get_feature_names_out(categorical_cols)
new_columns


# adding the columns to the dataframe
sex_onehot[new_columns] = ecoded_values

# remove the columns with object datatype sex
sex_onehot.drop(columns=['sex'], inplace = True)
sex_onehot

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male
0,0,3,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,1.0
1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0
2,1,3,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1.0,0.0
3,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1.0,0.0
4,0,3,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0.0,1.0
887,1,1,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1.0,0.0
888,0,3,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,1.0,0.0
889,1,1,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0.0,1.0
890,0,3,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.0,1.0