**22/12/2025**

**Scalling**

In [1]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.DataFrame({
    'age' : [20, 50, 100],
    'income' : [20000, 50000, 100000]
})

#upscale/downscale
scaler = MinMaxScaler()

# Normalization
# you want to check what the data will look like in a scale of 0 to 1.
normalize_data = scaler.fit_transform(data)
normalize_data

array([[0.   , 0.   ],
       [0.375, 0.375],
       [1.   , 1.   ]])

In [4]:
df_normalized = pd.DataFrame(normalize_data, columns=['age', 'income'])
df_normalized

     age  income
0  0.000   0.000
1  0.375   0.375
2  1.000   1.000

- Why do we normalize data? why do we need to normalize data for machine algorithm
    - easier to calculate

- a lot of preference to salary over age in the given example
- our models only use numbers

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
std_scaler = StandardScaler()

std_data = std_scaler.fit_transform(data)
std_data
# you got the z-score transformations for each data point

array([[-1.1111678 , -1.1111678 ],
       [-0.20203051, -0.20203051],
       [ 1.31319831,  1.31319831]])

In [8]:
data

   age  income
0   20   20000
1   50   50000
2  100  100000

In [7]:
df_std_data = pd.DataFrame(std_data, columns=['age', 'income'])
df_std_data

        age    income
0 -1.111168 -1.111168
1 -0.202031 -0.202031
2  1.313198  1.313198

**Feature Encoding**
    - ML models need numbers

- label encoding
- one hot encoding

**Feature Scaling**
- to avoid bias due to large ranges of some features
    - normalization
    - standardization